root: /
baseurl: /filtering.js

theme: minima
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/robertpainsi/filtering.js" }
header_pages:
  - README.md
  - guide.md
  - documentation.md
  - api.md
  - examples.md

markdown: CommonMarkGhPages
commonmark:
  options: [ "UNSAFE", "SMART", "FOOTNOTES" ]
  extensions: [ "strikethrough", "autolink", "table" ]

google_analytics: G-NY309E0RVD

plugins:
  - github-pages
  - jemoji
